# import = ["/home/user/.config/alacritty/themes/custom.toml"]


[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
# opacity = 0.92
opacity = 0.90
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 8.6

[cursor]
style = "Beam"  # or "Block", "Underline", etc.
