#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor primary -d 1 2 3 4 5 6 7 8

# Рамки и отступы
bspc config focused_border_color "#9db8e7"
bspc config normal_border_color "#1f222b"
bspc config border_width 1
bspc config window_gap 0
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config presel_feedback_color "#9db8e7"

# Коэффициент разделение. Сколько процентов останется от родительского окна при открытии нового
bspc config split_ratio          0.52

# Отступы и рамки, когда открыто одно окно
bspc config borderless_monocle true
bspc config gapless_monocle true

# Правила приложений

xrdb merge $HOME/.Xresources &
ssh-agent &

bash $HOME/.config/bspwm/scripts/battery-alert.sh &
bash $HOME/.config/bspwm/scripts/dunst_start.sh &
bash $HOME/.config/bspwm/scripts/redshift_start.sh &
bash $HOME/.config/bspwm/scripts/picom_start.sh &
bash $HOME/.config/bspwm/scripts/feh_start.sh & 
bash $HOME/.config/bspwm/scripts/polybar_start.sh &


obsidian
