#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor primary -d 1 2 3 4 5 6 7 8

bspc config border_width 1
bspc config split_ratio 0.52
bspc config window_gap 0
bspc config borderless_monocle true
bspc config gapless_monocle true

xrdb merge $HOME/.Xresources &

xsetroot -cursor_name left_ptr
setxkbmap -option grp:alt_shift_toggle us,ru
xset r rate 200 40

bash $HOME/.config/bspwm/scripts/battery-alert.sh &
bash $HOME/.config/bspwm/scripts/dunst_start.sh &
bash $HOME/.config/bspwm/scripts/redshift_start.sh &
bash $HOME/.config/bspwm/scripts/flameshot_start.sh &
bash $HOME/.config/bspwm/scripts/polybar_start.sh &
