[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0
blur = false

[font]
#normal.family = "JetBrainsMono Nerd Font"
normal.family = "Cascadia Code"
# size = 8.6
size = 9.2

[cursor]
style = "Beam"  # or "Block", "Underline", etc.
