if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# load Zinit
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"

# load Powerlevel10k theme (async)
zinit ice depth=1; zinit light romkatv/powerlevel10k

# syntax highlighting fast, but not beautiful(async)
zinit ice wait'0' lucid; zinit light zdharma-continuum/fast-syntax-highlighting

# syntax highlighting beautiful(async)
#zinit ice wait'0' lucid; zinit light zsh-users/zsh-syntax-highlighting

# autosuggestions (async)
#zinit ice wait'0' lucid; zinit light zsh-users/zsh-autosuggestions

# fast load (async)
zinit ice wait'0' lucid; zinit light zdharma-continuum/zinit-annex-bin-gem-node

# Load zsh-completions
zinit ice wait'0' lucid; zinit light zsh-users/zsh-completions

# init Powerlevel10k (theme setttings)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# aliases:
alias ls='ls --color=auto'
alias btw='neofetch'
